Update Game Maker UI
rightoneducation/righton-app pull request #197
Opened 2022-02-18 21:56 UTC by zach2025

- Added "Deletable" Questions (Visually deletes question but does not actually affect Game's Question set yet)
- Added summarized CCSS for Games, as well as toggleable CCSS Suggestion (The suggestion does change to Mashup when turned the Standards Aligned is unchecked, even though that is not a CCSS code)
- Shifted Game Image URL input to be inline with Phase timers
- Added preliminary Helper Popovers (will be updated to Figma design when Jared's PR is merged since he has this functionality already created/coded)

2022-02-18 22:02 UTC, zach2025 commented
To avoid conflicts, I suggest merging Ray's PR into the sprint branch first. Then, I will pull his changes on my local machine, resolve any conflicts/changed code that could affect his functionality (i.e. change the URL pathing to match that of the new URL pathing of Game Maker), and then push those directly to this remote version of my local branch. At that time the branch can be merged.

2022-02-18 22:18 UTC, EricNguyen-B approved these changes

2022-02-21 00:03 UTC, maniramezan commented
Would be nice to have a screenshot or the video to show the changes in action

2022-02-21 01:00 UTC, maniramezan requested changes

2022-02-21 22:36 UTC, maniramezan approved these changes
LGTM ❤️

2022-02-23 15:45 UTC, merged