Ray wu  add question form
rightoneducation/righton-app pull request #200
Opened 2022-02-23 21:17 UTC by RWu603

Updated the location for add question file.

2022-02-23 21:32 UTC, zach2025 requested changes
Most of it looks good, just a few little things that need to be changed

2022-02-23 21:32 UTC, zach2025 commented on web/src/components/GameMaker.jsx
> +            <Grid container xs={2}></Grid>
I think this was accidentally repeated so this line can be removed since it is already in line 302

2022-02-23 21:32 UTC, zach2025 commented on web/src/components/AddQuestion.jsx
> +  const handleColoneQuestion = async (question) => {
nitpick: misspelling

2022-02-23 21:32 UTC, zach2025 commented on web/src/components/AddQuestion.jsx
> +          <button className={classes.greenButton} color="primary" type="button" variant="contained" onClick={() => handleColoneQuestion(questions[index-1])}>Add to Game</button>
nitpick: misspelling (only change if the misspelling of the actual function above on line 119 because those names need to match)

2022-02-23 22:52 UTC, zach2025 approved these changes

2022-03-08 21:12 UTC, EricNguyen-B approved these changes
This looks good to me!

2022-03-08 21:18 UTC, merged